project/customers/models.py
from apiflask import Schema
from apiflask.fields import String
from project import db, app
import re
from sqlalchemy.orm import validates


# Customer model
class Customer(db.Model):
    __tablename__ = 'customers'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique=True, index=True)
    city = db.Column(db.String(64))
    age = db.Column(db.Integer)

    name_pattern = re.compile('^[a-z \'"-]{1,64}$', re.IGNORECASE)
    city_pattern = re.compile('^[a-z \'"-]{1,64}$', re.IGNORECASE)

    def __init__(self, name, city, age):
        self.name = name
        self.city = city
        self.age = age

    def __repr__(self):
        return f"Customer(ID: {self.id}, Name: {self.name}, City: {self.city}, Age: {self.age})"

    @validates('name')
    def validate_name(self, _, name):
        name = str(name)
        (min_len, max_len) = (1, 64)
        if not min_len <= len(name) <= max_len:
            raise ValueError(f'Expected name to have length between {min_len} and {max_len}, but it has length equal to {len(name)} instead')
        if re.fullmatch(self.name_pattern, name) is None:
            raise ValueError(f'Provided name value does not match pattern {self.name_pattern}')
        return name

    @validates('city')
    def validate_city(self, _, city):
        city = str(city)
        (min_len, max_len) = (1, 64)
        if not min_len <= len(city) <= max_len:
            raise ValueError(f'Expected city to have length between {min_len} and {max_len}, but it has length equal to {len(city)} instead')
        if re.fullmatch(self.city_pattern, city) is None:
            raise ValueError(f'Provided city value does not match pattern {self.city_pattern}')
        return city

    @validates('age')
    def validate_age(self, _, age):
        age = int(age)
        (min_value, max_value) = (0, 200)
        if not min_value <= age <= max_value:
            raise ValueError(f'Expected age to be between {min_value} and {max_value}, but it is {age} instead')
        return age


with app.app_context():
    db.create_all()


class CreateCustomerSchema(Schema):
    name = String(metadata={'description': 'Customer name.'})
    city = String(metadata={'description': 'City where customer lives.'})
    age = String(metadata={'description': 'Customer age.'})


class EditCustomerSchema(Schema):
    name = String(metadata={'description': 'Modified customer name.'})
    city = String(metadata={'description': 'Modified customer city name.'})
    age = String(metadata={'description': 'Modified customer age.'})

project/books/forms.py
# Form imports
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SelectField, SubmitField
from wtforms.validators import DataRequired


# Flask forms (wtforms) allow you to easily create forms in format:
class CreateBook(FlaskForm):
    name = StringField('Book Name', validators=[DataRequired()])
    author = StringField('Author')
    year_published = IntegerField('Year Published', validators=[DataRequired()])
    book_type = SelectField('Book Type', choices=[('2days', 'Up to 2 days'), ('5days', 'Up to 5 days'), ('10days', 'Up to 10 days')], validators=[DataRequired()])
    submit = SubmitField('Create Book')

project/customers/forms.py
# Form imports
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SubmitField
from wtforms.validators import DataRequired


# Flask forms (wtforms) allow you to easily create forms in this format:
class CreateCustomer(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])  
    city = StringField('City', validators=[DataRequired()])
    age = IntegerField('Age', validators=[DataRequired()])
    submit = SubmitField('Create Customer')

project/loans/forms.py
# Form imports
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, IntegerField
from wtforms.fields import DateField
from wtforms.validators import DataRequired


# Flask forms (wtforms) allow you to easily create forms in format:
class CreateLoan(FlaskForm):
    customer_name = StringField('Customer Name', validators=[DataRequired()])
    book_name = StringField('Book Name', validators=[DataRequired()])
    loan_date = DateField('Loan Date', format='%Y-%m-%d', validators=[DataRequired()])
    return_date = DateField('Return Date', format='%Y-%m-%d', validators=[DataRequired()])

    # Fields for capturing original book details
    original_author = StringField('Original Author', validators=[DataRequired()])
    original_year_published = IntegerField('Original Year Published', validators=[DataRequired()])
    original_book_type = StringField('Original Book Type', validators=[DataRequired()])

    submit = SubmitField('Create Loan')

project/books/__init__.py
# init file

project/books/views.py
from apiflask import APIBlueprint
from flask import render_template, request, redirect, url_for, jsonify
from project import db
from project.books.models import Book, CreateBookSchema, EditBookSchema


# Blueprint for books
books = APIBlueprint('books', __name__, template_folder='templates', url_prefix='/books')


# Route to display books in HTML
@books.route('/', methods=['GET'])
def list_books():
    # Fetch all books from the database
    books = Book.query.all()
    print('Books page accessed')
    return render_template('books.html', books=books)


# Route to fetch books in JSON format
@books.route('/json', methods=['GET'])
def list_books_json():
    # Fetch all books from the database and convert to JSON
    books = Book.query.all()
    # Create a list of dictionaries representing each book with the required fields
    book_list = [{'name': book.name, 'author': book.author, 'year_published': book.year_published, 'book_type': book.book_type} for book in books]
    return jsonify(books=book_list)


# Route to create a new book
@books.route('/create', methods=['POST'])
@books.input(CreateBookSchema)
def create_book(json_data: CreateBookSchema):
    data = json_data

    new_book = Book(name=data['name'], author=data['author'], year_published=data['year_published'], book_type=data['book_type'])

    try:
        # Add the new book to the session and commit to save to the database
        db.session.add(new_book)
        db.session.commit()
        print('Book added successfully')
        return redirect(url_for('books.list_books'))
    except Exception as e:
        # Handle any exceptions, such as database errors
        db.session.rollback()
        print('Error creating book')
        return jsonify({'error': f'Error creating book: {str(e)}'}), 500


# Route to update an existing book
@books.route('/<int:book_id>/edit', methods=['POST'])
@books.input(EditBookSchema)
def edit_book(book_id, json_data: EditBookSchema):
    # Get the book with the given ID
    book = Book.query.get(book_id)
    
    # Check if the book exists
    if not book:
        print('Book not found')
        return jsonify({'error': 'Book not found'}), 404

    try:
        # Get data from the request as JSON
        data = json_data
        
        # Update book details
        book.name = data.get('name', book.name)  # Update if data exists, otherwise keep the same
        book.author = data.get('author', book.author)
        book.year_published = data.get('year_published', book.year_published)
        book.book_type = data.get('book_type', book.book_type)
        
        # Commit the changes to the database
        db.session.commit()
        print('Book edited successfully')
        return jsonify({'message': 'Book updated successfully'})
    except Exception as e:
        # Handle any exceptions
        db.session.rollback()
        print('Error updating book')
        return jsonify({'error': f'Error updating book: {str(e)}'}), 500


# Route to fetch existing book data for editing
@books.route('/<int:book_id>/edit-data', methods=['GET'])
def get_book_for_edit(book_id):
    # Get the book with the given ID
    book = Book.query.get(book_id)
    
    # Check if the book exists
    if not book:
        print('Book not found')
        return jsonify({'success': False, 'error': 'Book not found'}), 404

    # Create a dictionary representing the book data
    book_data = {
        'name': book.name,
        'author': book.author,
        'year_published': book.year_published,
        'book_type': book.book_type
    }
    
    return jsonify({'success': True, 'book': book_data})


# Route to delete a book
@books.route('/<int:book_id>/delete', methods=['POST'])
def delete_book(book_id):
    book = Book.query.get(book_id)
    if not book:
        print('Book not found')
        return jsonify({'error': 'Book not found'}), 404

    try:
        # Delete the book from the database
        db.session.delete(book)
        db.session.commit()
        print('Book deleted successfully')
        return redirect(url_for('books.list_books'))
    except Exception as e:
        # Handle any exceptions, such as database errors
        db.session.rollback()
        print('Error deleting book')
        return jsonify({'error': f'Error deleting book: {str(e)}'}), 500


# Route to get book details based on book name
@books.route('/details/<string:book_name>', methods=['GET'])
def get_book_details(book_name):
        # Find the book by its name
        book = Book.query.filter_by(name=book_name).first()

        if book:
            book_data = {
                'name': book.name,
                'author': book.author,
                'year_published': book.year_published,
                'book_type': book.book_type
            }
            return jsonify(book=book_data)
        else:
            print('Book not found')
            return jsonify({'error': 'Book not found'}), 404

project/core/views.py
from typing import Optional

from apiflask import APIBlueprint
from flask import jsonify, render_template
from flask_jwt_extended import create_access_token, jwt_required, get_jwt_identity
from project import db
from project.core.models import User, CreateUserSchema, LogInSchema


# Blueprint for core
core = APIBlueprint('core', __name__, template_folder='templates', static_folder='static')


# Route to homepage
@core.route('/')
def index():
    print('Homepage accessed')
    return render_template('index.html')


@core.route("/login", methods=["POST"])
@core.doc(responses=[200, 401])
@core.input(LogInSchema)
def login(json_data: LogInSchema):
    username = json_data.get("username", None)
    password = json_data.get("password", None)
    if username is None or password is None:
        return jsonify({"msg": "Missing username or password"}), 401
    print(User.query.all())
    user: Optional[User] = User.query.filter_by(username=username).first()
    if user is None or user.password != password:
        return jsonify({"msg": "Bad username or password"}), 401

    token = create_access_token(identity=username)
    return jsonify(token=token)


@core.route("/register", methods=["POST"])
@core.doc(responses=[200, 401, 500])
@core.input(CreateUserSchema)
def register(json_data: CreateUserSchema):
    username = json_data.get("username", None)
    password = json_data.get("password", None)
    if username is None or password is None:
        return jsonify({"msg": "Missing username or password"}), 401
    try:
        new_user = User(username=username, password=password)
        db.session.add(new_user)
        db.session.commit()
        print('User added successfully')
    except Exception as e:
        db.session.rollback()
        print('Error creating user')
        return jsonify({'error': f'Error creating user: {str(e)}'}), 500

    token = create_access_token(identity=username)
    return jsonify(token=token)


@core.route("/protected", methods=["GET"])
@core.doc(security="HTTPBearerAuth", responses=[200, 401])
@jwt_required()
def protected():
    current_user = get_jwt_identity()
    return jsonify(username=current_user), 200

project/customers/__init__.py
# init file

project/customers/views.py
from apiflask import APIBlueprint
from flask import render_template, request, redirect, url_for, jsonify
from project import db
from project.customers.models import Customer, CreateCustomerSchema, EditCustomerSchema


# Blueprint for customers
customers = APIBlueprint('customers', __name__, template_folder='templates', url_prefix='/customers')


# Route to display customers in HTML
@customers.route('/', methods=['GET'])
def list_customers():
    # Fetch all customers from the database
    customers = Customer.query.all()
    print('Customers page accessed')
    return render_template('customers.html', customers=customers)


# Route to fetch customers in JSON format
@customers.route('/json', methods=['GET'])
def list_customers_json():
    # Fetch all customers from the database and convert to JSON
    customers = Customer.query.all()
    customer_list = [{'name': customer.name, 'city': customer.city, 'age': customer.age} for customer in customers]
    return jsonify(customers=customer_list)


# Route to create a new customer
@customers.route('/create', methods=['POST'])
@customers.input(CreateCustomerSchema, location='form')
def create_customer(form_data: CreateCustomerSchema):
    data = form_data
    # Check if all required fields are in the form data
    required_fields = ['name', 'city', 'age']
    if not all(field in data for field in required_fields):
        print('Invalid form data')
        return jsonify({'error': 'Invalid form data'}), 400

    # Create a new customer with all fields
    new_customer = Customer(
        name=data['name'],
        city=data['city'],
        age=data['age'],
    )

    try:
        db.session.add(new_customer)
        db.session.commit()
        print('Customer added successfully')
        return redirect(url_for('customers.list_customers'))
    except Exception as e:
        db.session.rollback()
        print(f'Error creating customer: {str(e)}')
        return jsonify({'error': f'Error creating customer: {str(e)}'}), 500


# Route to fetch customer data for editing
@customers.route('/<int:customer_id>/edit-data', methods=['GET'])
def edit_customer_data(customer_id):
    # Get the customer with the given ID
    customer = Customer.query.get(customer_id)

    if customer:
        # Convert customer data to a dictionary
        customer_data = {
            'name': customer.name,
            'city': customer.city,
            'age': customer.age
        }
        return jsonify({'success': True, 'customer': customer_data}), 200
    else:
        print('Customer not found')
        return jsonify({'error': 'Customer not found'}), 404


# Route to update an existing customer
@customers.route('/<int:customer_id>/edit', methods=['POST'])
@customers.input(EditCustomerSchema, location='form')
def edit_customer(customer_id, form_data: EditCustomerSchema):
    # Get the customer with the given ID
    customer = Customer.query.get(customer_id)

    # Check if the customer exists
    if not customer:
        print('Customer not found')
        return jsonify({'error': 'Customer not found'}), 404

    try:
        # Get data from the request
        data = form_data

        # Update customer details
        customer.name = data['name']
        customer.city = data['city']
        customer.age = data['age']

        # Commit the changes to the database
        db.session.commit()
        print('Customer updated succesfully')
        return redirect(url_for('customers.list_customers'))
    except Exception as e:
        # Handle any exceptions
        db.session.rollback()
        print('Error updating customer')
        return jsonify({'error': f'Error updating customer: {str(e)}'}), 500


# Route to delete a customer
@customers.route('/<int:customer_id>/delete', methods=['POST'])
def delete_customer(customer_id):
    customer = Customer.query.get(customer_id)
    if not customer:
        print('Customer not found')
        return jsonify({'error': 'Customer not found'}), 404

    try:
        # Delete the customer from the database
        db.session.delete(customer)
        db.session.commit()
        print('Customer deleted successfully')
        return redirect(url_for('customers.list_customers'))
    except Exception as e:
        # Handle any exceptions, such as database errors
        db.session.rollback()
        print('Error deleting customer')
        return jsonify({'error': f'Error deleting customer: {str(e)}'}), 500

project/loans/__init__.py
# init file

project/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <title>Book Library</title>
</head>

<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{{ url_for('core.index') }}">Book Library</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('core.index') }}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('books.list_books') }}">Books</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('customers.list_customers') }}">Customers</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('loans.list_loans') }}">Loans</a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container">
        {% block content %}{% endblock %}
    </div>

    <!-- Bootstrap JavaScript -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <!-- jQuery UI -->
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <!-- Axios -->
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>

</body>

</html>

project/templates/books.html
{% extends 'base.html' %}
{% block content %}


<div class="container">
    <h1 class="my-4">Books</h1>

    <!-- Link to trigger modal -->
    <button type="button" class="btn btn-success" data-toggle="modal" data-target="#addBookModal">
        Add New Book
    </button>

    <!-- Search box -->
    <input type="text" id="searchInput" class="form-control mb-3" placeholder="Search for books..">

    <!-- Table to list books -->
    <table class="table table-bordered">
        <!-- Table header -->
        <thead>
            <tr>
                <th>Name</th>
                <th>Author</th>
                <th>Year Published</th> <!-- New field: Year Published -->
                <th>Type</th> <!-- New field: Type -->
                <th>Actions</th>
            </tr>
        </thead>
        <!-- Table body -->
        <tbody>
            <!-- Loop through books and display each book -->
            {% for book in books %}
            <tr>
                <td>{{ book.name | safe }}</td>
                <td>{{ book.author | safe }}</td>
                <td>{{ book.year_published }}</td> <!-- Display Year Published -->
                <td>{{ book.book_type }}</td> <!-- Display Book Type -->
                <td>
                    <!-- Inside the <td> for "Edit" button -->
                    <button class="btn btn-warning btn-sm" onclick="editBook({{ book.id }})">Edit</button>

                    <!-- Inside the <td> for "Delete" button -->
                    <button class="btn btn-danger btn-sm" onclick="deleteBook({{ book.id }})">Delete</button>


                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>


<!-- Add Book Modal -->
<div class="modal fade" id="addBookModal" tabindex="-1" role="dialog" aria-labelledby="addBookModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addBookModalLabel">Add New Book</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <!-- Add Book Form -->
                <form id="addBookForm">
                    <div class="form-group">
                        <label for="name">Name</label>
                        <input type="text" class="form-control" id="name" placeholder="Enter book name" required>
                    </div>
                    <div class="form-group">
                        <label for="author">Author</label>
                        <input type="text" class="form-control" id="author" placeholder="Enter author name" required>
                    </div>
                    <div class="form-group">
                        <label for="year_published">Year Published</label>
                        <input type="number" class="form-control" id="year_published" placeholder="Enter year published"
                            required>
                    </div>
                    <div class="form-group">
                        <label for="book_type">Type</label>
                        <select class="form-control" id="book_type" required>
                            <option value="2days">2 Days</option>
                            <option value="5days">5 Days</option>
                            <option value="10days">10 Days</option>
                        </select>
                    </div>
                    
                    <button type="submit" class="btn btn-primary">Add Book</button>
                </form>
            </div>
        </div>
    </div>
</div>


<!-- Edit Book Modal -->
<div class="modal fade" id="editBookModal" tabindex="-1" role="dialog" aria-labelledby="editBookModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editBookModalLabel">Edit Book</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <!-- Edit Book Form -->
                <form id="editBookForm">
                    <div class="form-group">
                        <label for="edit_name">Name</label>
                        <input type="text" class="form-control" id="edit_name" placeholder="Enter book name" required>
                    </div>
                    <div class="form-group">
                        <label for="edit_author">Author</label>
                        <input type="text" class="form-control" id="edit_author" placeholder="Enter author name"
                            required>
                    </div>
                    <div class="form-group">
                        <label for="edit_year_published">Year Published</label>
                        <input type="number" class="form-control" id="edit_year_published"
                            placeholder="Enter year published" required>
                    </div>
                    <div class="form-group">
                        <label for="edit_book_type">Type</label>
                        <select class="form-control" id="edit_book_type" required>
                            <option value="2days">2 Days</option>
                            <option value="5days">5 Days</option>
                            <option value="10days">10 Days</option>
                        </select>
                    </div>

                    <button type="button" class="btn btn-primary" id="saveEditBookButton">Save Changes</button>
                </form>
            </div>
        </div>
    </div>
</div>


<!-- Include Axios -->
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>

<!-- Custom JavaScript file (books.js) -->
<script src="{{ url_for('static', filename='js/books.js') }}"></script>


{% endblock %}

project/templates/customers.html
{% extends 'base.html' %}

{% block content %}


<div class="container">
    <h1 class="my-4">Customers</h1>

    <!-- Link to trigger modal -->
    <button type="button" class="btn btn-success" data-toggle="modal" data-target="#addCustomerModal">
        Add New Customer
    </button>

    <!-- Search box -->
    <input type="text" id="searchInput" class="form-control mb-3" placeholder="Search for customers..">

    <!-- Table to list customers -->
    <table class="table table-bordered">
        <!-- Table header -->
        <thead>
            <tr>
                <th>Name</th>
                <th>City</th> <!-- Changed from 'Author' to 'City' -->
                <th>Age</th>  <!-- Added 'Age' -->
                <th>Actions</th>
            </tr>
        </thead>
        <!-- Table body -->
        <tbody>
            <!-- Loop through customers and display each customer -->
            {% for customer in customers %}
            <tr>
                <td>{{ customer.name | safe }}</td>
                <td>{{ customer.city | safe }}</td>  <!-- Display 'city' instead of 'author' -->
                <td>{{ customer.age }}</td>  <!-- Display 'age' -->
                <td>
                    <a href="#" class="btn btn-warning btn-sm" onclick="editCustomer({{ customer.id }})">Edit</a>
                    <button class="btn btn-danger btn-sm" onclick="deleteCustomer({{ customer.id }})">Delete</button>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>


<!-- Add Customer Modal -->
<div class="modal fade" id="addCustomerModal" tabindex="-1" role="dialog" aria-labelledby="addCustomerModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addCustomerModalLabel">Add New Customer</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <!-- Add Customer Form -->
                <form id="addCustomerForm">
                    <div class="form-group">
                        <label for="name">Name</label>
                        <input type="text" class="form-control" id="name" placeholder="Enter customer name" required>
                    </div>
                    <div class="form-group">
                        <label for="city">City</label>
                        <input type="text" class="form-control" id="city" placeholder="Enter city" required>
                    </div>
                    <div class="form-group">
                        <label for="age">Age</label>
                        <input type="number" class="form-control" id="age" placeholder="Enter age" required>
                    </div>



                    <button type="submit" class="btn btn-primary">Add Customer</button>
                </form>
            </div>
        </div>
    </div>
</div>


<!-- Edit Customer Modal -->
<div class="modal fade" id="editCustomerModal" tabindex="-1" role="dialog" aria-labelledby="editCustomerModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editCustomerModalLabel">Edit Customer</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <!-- Edit Customer Form -->
                <form id="editCustomerForm">
                    <div class="form-group">
                        <label for="edit_name">Name</label>
                        <input type="text" class="form-control" id="edit_name" placeholder="Enter customer name" required>
                    </div>
                    <div class="form-group">
                        <label for="edit_city">City</label>
                        <input type="text" class="form-control" id="edit_city" placeholder="Enter city" required>
                    </div>
                    <div class="form-group">
                        <label for="edit_age">Age</label>
                        <input type="number" class="form-control" id="edit_age" placeholder="Enter age" required>
                    </div>
                    <button type="button" class="btn btn-primary" id="saveEditCustomerButton">Save Changes</button>
                </form>
            </div>
        </div>
    </div>
</div>


<!-- Include jQuery -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<!-- Include Axios -->
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>

<!-- Custom JavaScript file (customers.js) -->
<script src="{{ url_for('static', filename='js/customers.js') }}"></script>


{% endblock %}

project/templates/index.html
{% extends 'base.html' %}

{% block content %}
<br>
    <h1>Welcome to the Book library</h1>

{% endblock %}